#!/bin/bash
###
### Copyright 2014, Boundary
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

PROJECT=$(echo $BOUNDARY_PREMIUM_API_TOKEN | awk -F'-' '{print $2}')

if [ $# -gt 1 ]
then
  echo "usage $(basename $0) [match]"
  exit 1
elif  [ $# -eq 1 ]
then
   match="$1"
else
  :
fi
AUTH="$BOUNDARY_PREMIUM_EMAIL:$BOUNDARY_PREMIUM_API_TOKEN"
URL="https://$BOUNDARY_PREMIUM_API_HOST/project/$PROJECT/metricsEdit"
FIELDS="{name: .name, description: .description,displayName: .displayName,displayNameShort: .displayNameShort,unit: .unit,defaultAggregate: .defaultAggregate,defaultResolutionMS: .defaultResolutionMS}"

if [ -z "$match" ]
then
  curl -s -u "$AUTH" "$URL" | jq "." #| $FIELDS"
else
  curl -s -u "$AUTH" "$URL" | jq ".result[] | select(.name | contains(\"$match\")) | $FIELDS"
fi
