#!/bin/bash

#if [ $# -ne 1 ]
#then
#  echo "usage: $(basename $0) <name>"
#  exit 1
#fi
curl -u "$BOUNDARY_METRICS_EMAIL:$BOUNDARY_METRICS_TOKEN" 'https://metrics-api.boundary.com/project/16/metricsEdit'
