#!/bin/bash
###
### Copyright 2014-2015 Boundary, Inc.
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

Useage() {
  echo "usage: $(basename $0) metric_id [ <start> <end> ]"
#  echo ""
#  echo "where:"
#  echo ""
#  echo "metric_id - Unique id of the metric"
#  echo "start - "
#  echo "end - "
  exit 1
}

set -x

typeset -r METRIC_ID=$1
typeset -r START_DT=$(date -d "$2" '+%s')
typeset -r END_DT=$(date -d "$3" '+%s')
typeset -r START=$(( $START_DT * 10))
typeset -r END=$(($END_DT * 10))
typeset -r AUTH="$BOUNDARY_EMAIL:$BOUNDARY_API_TOKEN"

if [ $# -eq 1 ]
then
  URL="https://$BOUNDARY_API_HOST/v1/measurements/$METRIC_ID?agg=AVG"
elif [ $# -eq 3 ]
then
  URL="https://$BOUNDARY_API_HOST/v1/measurements/$METRIC_ID?start=$START&end=$END&agg=AVG"
else
  Useage
fi
URL="https://$BOUNDARY_API_HOST/v1/measurements/$METRIC_ID?start=$START&end=$END&agg=AVG"

curl -X GET -i -u"$AUTH" $URL

