#!/bin/bash
###
### Copyright 2014-2015 Boundary, Inc.
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

if [ $# -ne 3 ]
then
   echo "usage: $(basename $0) metric measure source"
   exit 1
fi
timestamp=$(date +%s)

typeset -r metric=$1
typeset -r measure=$2
typeset -r source=$3

typeset -r PAYLOAD="{\"source\": \"$source\", \"metric\": \"$metric\", \"measure\": $measure, \"timestamp\": $timestamp}"
typeset -r AUTH="$BOUNDARY_EMAIL:$BOUNDARY_API_TOKEN"
typeset -r HEADER="Content-Type: application/json"
typeset -r URI="https://$BOUNDARY_API_HOST/v1/measurements" 

curl -i -X POST -u "$AUTH" -H "$HEADER" -d "$PAYLOAD" "$URI" #| jq '.'
