#!/bin/bash

if [ $# -ne 1 ]
then
  echo "usage: $(basename $0) <name>"
  exit 1
fi
curl -X DELETE -u "$BOUNDARY_METRICS_EMAIL:$BOUNDARY_METRICS_TOKEN" "https://$BOUNDARY_METRICS_API_HOST/v1/metrics/$1"
