#!/bin/bash 
###
### Copyright 2014-2015 Boundary, Inc.
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

Usage() {
  echo "usage: $(basename $0) <name> <display-name> <display-name_short> <description> <aggregate> <unit>"
  echo "where"
  echo "  name - Name of the metric"
  echo "  display-name - Name displayed in the Web UI"
  echo "  display-name-short - Shorter display name"
  echo "  description - Description of the metric (also used as tooltip)"
  echo "  aggregate - Type of aggregate (sum, avg, max, or min)"
  echo "  unit - Type of measurement (percent, number, bytecount, or duration )"
  echo "  defaultResolutionMS - Type of measurement (percent, number, bytecount, or duration )"
}

FormatPayload() {
  typeset -r name=$1
  typeset -r description=$2
  typeset -r displayName=$3
  typeset -r displayNameShort=$4
  typeset -r unit=$5
  typeset -r defaultAggregate=$6
  typeset -r defaultResolutionMS=$6

  PAYLOAD=$(cat <<EOF
    {"name": "$name",
     "description": "$description",
     "displayName": "$displayName",
     "displayNameShort": "$displayNameShort",
     "unit": "$unit",
     "defaultAggregate": "$defaultAggregate",
     "defaultResolutionMS": "$defaultResolutionMS"
    }
EOF
)

 echo $PAYLOAD
}


Main() {
  if [ $# -ne 7 ]
  then
    Usage
    exit 1
  fi

  typeset -r name=$1
  typeset -r display_name=$2
  typeset -r display_name_short=$3
  typeset -r description=$4
  typeset -r aggregate=$5
  typeset -r unit=$6
  typeset -r resolution=$7

  typeset -r PAYLOAD=$(FormatPayload "$name" "$description" "$display_name" "$display_name_short" "$unit" "$aggregate" "$resolution")

  AUTH="$BOUNDARY_EMAIL:$BOUNDARY_API_TOKEN"
  HEADER="Content-Type: application/json" 
  URI="https://$BOUNDARY_API_HOST/v1/metrics/$name" #| jq '.'

  curl -s -X PUT -u "$AUTH" -H "$HEADER" -d "$PAYLOAD" "$URI" #| jq '.'
}

Main "$@"

