#!/bin/bash

if [ $# -ne 1 ]
then
  echo "usage: $(basename) <match>"
  exit 1
fi

#$BOUNDARY_API_SHELL_HOME/metric-list | jq ".result[] | select(.name | contains(\"$1\"))"
jq ".result[] | select(.name | contains(\"$1\")) | {name: .name, displayName: .displayName}"
