#!/bin/bash
###
### Copyright 2014-2015 Boundary, Inc.
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

if [ $# -ne 3 ]
then
  echo "usage: $(basename $0) <plugin name> <organization_name> <repository_name>"
  exit 1
fi

AUTH="$BOUNDARY_EMAIL:$BOUNDARY_API_TOKEN"
URI="https://$BOUNDARY_API_HOST/v1/plugins/private/$1/$2/$3" 
curl -s -X PUT -u "$AUTH" "$URI" | jq '.'
