#!/bin/bash

###
### Copyright 2014, Boundary
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###


Main() {

if [ $# -ne 1 ]
then
   echo "usage: $(basename $0) <event>"
   exit 1
fi
typeset -r event=$1
#echo $event
payload="{$event}"

curl -i -X POST -u "${BOUNDARY_API_KEY}": -H "Content-Type: application/json" -d "$payload" "https://api.boundary.com/${BOUNDARY_ORG_ID}/events" 

}

Main "$@"
