#!/bin/bash

###
### Copyright 2013, Boundary
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

processQuery() {
   typeset -r event_query=$1
   queryEvents "$event_query"
}

queryEvents() {
   typeset -r q=$1
   curl -s -u "$BOUNDARY_API_KEY:" "https://$BOUNDARY_API_HOST/$BOUNDARY_ORG_ID/events?q=$q" | jq '.'
}

if [ $# -ne 1 ]
then
   echo "usage: $(basename $0) <query>"
   exit 1
fi
processQuery "$@" 
