#!/bin/bash
###
### Copyright 2014, Boundary
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

if [ $# -ne 3 ]
then
  echo "usage $(basename) [account-id] [source] [type-name]"
  exit 1
fi

# Set command line arguments to read-only variables
typeset account_id=$1
typeset source=$2
typeset type_name=$3

AUTH="$BOUNDARY_PREMIUM_EMAIL:$BOUNDARY_PREMIUM_API_TOKEN"
URL="https://$BOUNDARY_PREMIUM_API_HOST/account/$account_id/sourcetypes"
PAYLOAD="{\"source\": \"$source\", \"typename\": \"$type_name\", \"action\":\"remove\"}"

echo curl -s -X POST -u "$AUTH" -d "$PAYLOAD" "$URL" 
curl -s -X POST -u "$AUTH" -d "$PAYLOAD" "$URL" 
