#!/bin/bash

Main() {
if [ $# -ne 1 ]
then
   echo "usage: $(basename $0) name"
   exit 1
fi

event-create "\"title\": \"maintenance\", \"message\": \"Change ticket issued for $1\",\"status\": \"OPEN\", \"severity\": \"INFO\", \"source\": {\"ref\": \"$1\", \"type\": \"host\"}, \"fingerprintFields\": [\"@title\",\"hostname\"], \"properties\": {\"hostname\": \"$1\"}"
}

Main "$@"
