#!/bin/bash

Main() {
if [ $# -ne 1 ]
then
   echo "usage: $(basename $0) name"
   exit 1
fi

event-create "\"title\": \"Tripwire Started\", \"message\": \"coldStart\",\"status\": \"CLOSED\",\"source\": {\"ref\": \"$1\", \"type\": \"host\"}, \"fingerprintFields\": [\"hostname\",\"sysUpTimeInstance\"], \"properties\": {\"hostname\": \"$1\",\"sysUpTimeInstance\": \"0:00:00.00\"}"
}

Main "$@"
