#!/bin/bash

###
### Copyright 2013, Boundary
###
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###
###     http://www.apache.org/licenses/LICENSE-2.0
###
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.
###

APIHOST="api.boundary.com"
APICREDS=

print_help() {
  echo "./create_event -i ORGID -a APIKEY"
  exit 0
}
#    'title': 'example\nfoo',
#    'createdAt': '2014-04-14T23:31:36.635757',
#    'message': 'test',
#    'tags': ['example', 'test', 'stuff'],
#    'fingerprintFields': ['@title'],
#    'source': {
#        'ref': 'myhost',
#        'type': 'host'
#    }

#"organizationId":"",
#"sender":{"ref":"","type":"","name":"","properties":{}},

#   "createdAt":1397605089881,
#   "message":"davidg[89290]: Tue Apr 15 16:38:09 PDT 2014\n",
#   "severity":"INFO",
#   "properties":{
#      "facility":"LOCAL0",
#      "remote_address":"/127.0.0.1:54199"
#      "hostname":"Lerma.local",
#      "message":"davidg[89290]: Tue Apr 15 16:38:09 PDT 2014\n",
#   },

create_event() {
    PAYLOAD=$(cat <<EOF
{
    "createdAt": "2014-05-30T16:36:28.000Z", 
    "fingerprintFields": [
        "@title"
    ], 
    "message": "NOPARSE", 
    "organizationId": null, 
    "properties": {}, 
    "receivedAt": null, 
    "sender": {
        "ref": "javascript", 
        "type": "noparse"
    }, 
    "severity": "INFO", 
    "source": {
        "ref": "somehost", 
        "type": "host"
    }, 
    "status": "OPEN", 
    "title": "Test Message - 3"
}

EOF
)
  local LOCATION=`curl -is -v -X POST -H "Content-Type: application/json" \
  -d "$PAYLOAD" \
  -u "$1:" $2  \
        | grep Location \
        | sed 's/Location: //' \
        | sed 's/\(.*\)./\1/'`

  echo $LOCATION
}
Main() {
while getopts "h a:i:" opts
do
  case $opts in
    h) print_help;;
    i) APIID="$OPTARG";;
    a) APIKEY="$OPTARG";;
    [?]) print_help;;
  esac
done

if [ ! -z $APIID ]
  then
    if [ ! -z $APIKEY ]
      then
        URL="https://$APIHOST/$APIID/events"

        LOCATION=`create_event $APIKEY $URL`

        if [ ! -z $LOCATION ]
          then
            echo "An event was created at $LOCATION"
          else
            echo "No location header received, error creating event!"
            exit 1
        fi
      else
        print_help
      fi
else
  print_help
fi
}

curl -q -u '6OThKB6oaF4TkCXPFIWxoHuLzX1:' 'https://api.boundary.com/3ehRi7uZeeaTN12dErF5XOnRXjC/events'
